apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clouddental-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - clouddentaloffice.com
        - www.clouddentaloffice.com
      secretName: clouddentaloffice-tls
  rules:
    - host: clouddentaloffice.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portal
                port:
                  number: 5000
    - host: www.clouddentaloffice.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portal
                port:
                  number: 5000
